// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Asset struct {
	ID        uuid.UUID
	Symbol    string
	Price     string
	CreatedAt time.Time
	UpdatedAt time.Time
}
