// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Asset struct {
	ID        uuid.UUID
	Symbol    string
	Price     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Wallet struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type WalletAsset struct {
	ID        uuid.UUID
	Amount    string
	Shares    int32
	CreatedAt time.Time
	UpdatedAt time.Time
	WalletID  uuid.UUID
	AssetID   uuid.UUID
}
