version: '3'

services:
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres 
    volumes:
      - postgres-go-stock:/var/lib/postgresql/data

volumes:
  postgres-go-stock: